name = "HapppyMC Cinderworks Mod Pack"
author = "alittlehuaji"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d5cc302c33de18195f8c263efc2529a046f5d59569967f53c0f4118744b3a01"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
