name = "Cinderworks"
author = "alittlehuaji"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e220a3e049716e4617fa6ec133eb1538296b021aaa35428f695a241b23b9c3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"
