name = "Cinderworks"
author = "alittlehuaji"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b249ec8b85b1a44ac7d83ec19156f8bad1a5208c2e25451e289b41b77e8293dc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
